[pytest]
testpaths = tests  # Указываем каталог, где pytest должен искать тесты
python_files = test_*.py *_test.py # Указываем шаблоны имен файлов с тестами
addopts = -v -rA # Опции для подробного вывода
# Указываем папку для импорта модулей (если она отличается от места, где лежат тесты)
# python_paths = registration  # Раскомментируйте, если файлы с кодом в папке registration, а тесты в другом месте
#cov_source = registration/registration.py # Файл, который анализируем на покрытие кода